tests and readme updated
gilyes/node-weather-envcanada pull request #2
Opened 2017-11-10 11:41 UTC by BumbleB2na

To support more data exposed from forecast xml

2017-11-10 17:32 UTC, gilyes requested changes

2017-11-10 17:32 UTC, gilyes commented on lib/weather.js
> +                    windChillSummary: forecast.windChill[0].textSummary[0],
Thanks for the updates. One issue: apparently *windChill* value is not always in the dataset and in those cases this line will break.

2017-11-15 20:06 UTC, BumbleB2na commented
Oh, right. I've updated and it tests one of the forecasts that has no windChill.

2017-11-15 22:45 UTC, gilyes approved these changes

2017-11-15 22:46 UTC, gilyes commented
Thanks.

2017-11-15 22:46 UTC, closed without merging